import './globals.css'
import type { Metadata } from 'next';
import { Header, Footer } from '@/components';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className='min-h-full min-w-full overflow-x-hidden antialiased'>
        <Header />
        {children}
        <h1>sssss</h1>
        <Footer />
      </body>
    </html>
  );
}
